stages:
  - analyze
  # - build
  # - deploy
  # - notify

# variables:
#   PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/mobile.kship/flutter/bin:/opt/homebrew/opt/node@14/bin:/opt/homebrew/bin
#   GIT_CLONE_PATH: '$CI_BUILDS_DIR/$CI_JOB_ID/$CI_PROJECT_NAME'

before_script:
  - flutter --version
  - pwd

job_analyze:
  stage: analyze
  script:
    - bash scripts/pub_upgrade_all.sh
    - bash scripts/gen_asset.sh
    - bash scripts/gen_code_all.sh
job_analyze:
  stage: analyze
  script:
    - bash scripts/pub_upgrade.sh
    - bash scripts/gen_asset.sh
    - bash scripts/gen_code.sh
    - bash scripts/format_code.sh
    - git status
    - bash scripts/check_has_change.sh
    - flutter analyze
  only:
    - merge_requests
    - develop
    - beta
    - prod
    - tags
    - /^release-.*$/
  tags:
    - team-money-dev-mobile